# Generated by Django 5.2.3 on 2026-02-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_font_family_font_style_font_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
