# Generated by Django 5.2.3 on 2026-02-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_tool_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transformvariable',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='font',
            name='api_font_name_3b3d65_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasedtemplate',
            name='api_purchas_buyer_i_42df18_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasedtemplate',
            name='api_purchas_templat_77de59_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasedtemplate',
            name='api_purchas_trackin_91ff64_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasedtemplate',
            name='api_purchas_created_59fb6c_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='api_templat_type_d4ff45_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='api_templat_hot_25285e_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='api_templat_created_b81313_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='api_templat_tool_id_a5db6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='api_templat_is_acti_978198_idx',
        ),
        migrations.RemoveField(
            model_name='purchasedtemplate',
            name='svg',
        ),
        migrations.RemoveField(
            model_name='template',
            name='svg',
        ),
        migrations.RemoveField(
            model_name='transformvariable',
            name='created_at',
        ),
        migrations.AddField(
            model_name='template',
            name='svg_patches',
            field=models.JSONField(blank=True, default=list, help_text='Incremental edits (Figma-style)'),
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='font',
            name='family',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='font',
            name='font_file',
            field=models.FileField(upload_to='fonts/'),
        ),
        migrations.AlterField(
            model_name='font',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='font',
            name='style',
            field=models.CharField(default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='font',
            name='weight',
            field=models.CharField(default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasedtemplate',
            name='fonts',
            field=models.ManyToManyField(blank=True, related_name='purchased_templates', to='api.font'),
        ),
        migrations.AlterField(
            model_name='purchasedtemplate',
            name='svg_file',
            field=models.FileField(blank=True, null=True, upload_to='purchased_templates/svgs/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='crypto_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='dev_name_obfuscated',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='manual_purchase_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='owner_name_obfuscated',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='template',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='template_banners/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='fonts',
            field=models.ManyToManyField(blank=True, related_name='templates', to='api.font'),
        ),
        migrations.AlterField(
            model_name='template',
            name='svg_file',
            field=models.FileField(blank=True, help_text='Base SVG file storage', null=True, upload_to='templates/svgs/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='url',
            field=models.URLField(),
        ),
    ]
