# Generated by Django 5.2.3 on 2026-02-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtemplate',
            name='svg_patches',
            field=models.JSONField(blank=True, default=list, help_text='Incremental edits made by the user'),
        ),
    ]
