# Generated by Django 5.2.3 on 2026-02-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_purchasedtemplate_svg_patches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedtemplate',
            name='form_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='template',
            name='form_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
