# Generated by Django 5.2.3 on 2026-02-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_purchasedtemplate_form_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='disable_deposits',
            field=models.BooleanField(default=False, help_text='Lock the wallet top-up functionality temporarily'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='disable_new_signups',
            field=models.BooleanField(default=False, help_text='Temporarily block new users from creating accounts'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_global_announcement',
            field=models.BooleanField(default=False, help_text='Show the global banner to all users'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='exchange_rate_override',
            field=models.DecimalField(decimal_places=2, default=1650.0, help_text='Flat Dollar-to-Naira Exchange Rate (e.g. 1650)', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='global_announcement_link',
            field=models.URLField(blank=True, help_text='Optional link for global banner'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='global_announcement_text',
            field=models.TextField(blank=True, help_text='Text for global dashboard banner'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Instagram link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Block non-admins with a maintenance screen'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_topup_amount',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Minimum top-up amount in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Central support email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_link',
            field=models.URLField(blank=True, help_text='Telegram Group/Channel link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_link',
            field=models.URLField(blank=True, help_text='Twitter/X link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='crypto_address',
            field=models.CharField(blank=True, help_text='Fallback / Master BEP20 USDT Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='2349160914217', help_text='E.g. 2349160914217', max_length=50),
        ),
    ]
