# Generated by Django 5.2.3 on 2026-02-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_sitesettings_disable_deposits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='funding_whatsapp_number',
            field=models.CharField(blank=True, default='2349160914217', help_text='WhatsApp for manual deposits', max_length=50),
        ),
    ]
