# Generated by Django 5.2.3 on 2026-02-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_sitesettings_funding_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_community_link',
            field=models.URLField(blank=True, help_text='WhatsApp Community/Group Invite Link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Platform Support Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='2349160914217', help_text='Support WhatsApp Number (e.g. 234...)', max_length=50),
        ),
    ]
