# Generated by Django 5.2.3 on 2026-02-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_sitesettings_whatsapp_community_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_link',
            field=models.URLField(blank=True, help_text='TikTok link'),
        ),
    ]
