# Generated by Django 5.2.3 on 2026-07-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_tutorial_options_tutorial_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='deposit_promo_expiry_days',
            field=models.PositiveIntegerField(default=7, help_text='Days until a granted bonus expires (0 = never)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='deposit_promo_max_bonus',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Maximum bonus (USD) granted per deposit', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='deposit_promo_message',
            field=models.TextField(blank=True, default='', help_text='Optional promo copy for the popup/banner (blank = auto-generated)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='deposit_promo_min_amount',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Minimum deposit (USD) to qualify for the bonus', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='deposit_promo_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Bonus percentage of the deposit (e.g. 100.00 = 100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_deposit_promo',
            field=models.BooleanField(default=False, help_text='Enable the deposit bonus promo'),
        ),
    ]
