# Generated by Django 5.2.3 on 2026-08-12 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_sitesettings_deposit_promo_expiry_days_and_more'),
        ('wallet', '0005_wallet_bonus_balance_depositbonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCustomerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiIdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=24, unique=True)),
                ('secret_hash', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmbedSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('external_user_id', models.CharField(max_length=255)),
                ('allowed_origin', models.URLField(max_length=500)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('paid', 'Paid')], default='test', max_length=8)),
                ('prefill', models.JSONField(blank=True, default=dict)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchasedtemplate',
            name='external_user_id',
            field=models.CharField(blank=True, default='', help_text='Opaque end-user identifier supplied by the owning API customer', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='api_default_rate_limit',
            field=models.PositiveIntegerField(default=120, help_text='Requests per API key per minute'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='api_session_ttl_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Maximum lifetime of a hosted embed session'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='api_upgrade_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_api_access',
            field=models.BooleanField(default=False, help_text='Global API and embed kill-switch'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_api_upgrade',
            field=models.BooleanField(default=True, help_text='Charge the configured wallet amount before API activation'),
        ),
        migrations.AddIndex(
            model_name='purchasedtemplate',
            index=models.Index(fields=['buyer', 'external_user_id', '-created_at'], name='api_doc_tenant_ext_created_idx'),
        ),
        migrations.AddField(
            model_name='apicustomersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_customer_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apientitlement',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_entitlements', to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='apientitlement',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_entitlement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiidempotencyrecord',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to='api.purchasedtemplate'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiidempotencyrecord',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='api.apikey'),
        ),
        migrations.AddField(
            model_name='embedsession',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embed_sessions', to='api.apikey'),
        ),
        migrations.AddField(
            model_name='embedsession',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embed_session', to='api.purchasedtemplate'),
        ),
        migrations.AddField(
            model_name='embedsession',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_sessions', to='api.template'),
        ),
        migrations.AddField(
            model_name='embedsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user', 'revoked_at'], name='api_key_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='apiidempotencyrecord',
            index=models.Index(fields=['created_at'], name='api_idempotency_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='apiidempotencyrecord',
            constraint=models.UniqueConstraint(fields=('api_key', 'operation', 'key'), name='unique_api_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='embedsession',
            index=models.Index(fields=['user', 'status', '-created_at'], name='embed_user_status_created_idx'),
        ),
    ]
