# Generated by Django 5.2.3 on 2026-08-12 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_apicustomersettings_apientitlement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRenderJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('png', 'PNG'), ('pdf', 'PDF')], max_length=4)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='api/renders/%Y/%m/%d/')),
                ('output_size', models.PositiveBigIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_jobs', to='api.purchasedtemplate')),
                ('requested_by_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_jobs', to='api.apikey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_render_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='apiidempotencyrecord',
            name='render_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to='api.documentrenderjob'),
        ),
        migrations.AddIndex(
            model_name='documentrenderjob',
            index=models.Index(fields=['user', 'status', '-created_at'], name='render_user_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrenderjob',
            index=models.Index(fields=['expires_at'], name='render_expiry_idx'),
        ),
    ]
