# Generated by Django 5.2.3 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_embedsession_operation_and_document_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="api_tool_discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Global percentage discount applied to paid API documents",
                max_digits=5,
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesettings",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(api_tool_discount_percentage__gte=0)
                    & models.Q(api_tool_discount_percentage__lte=100)
                ),
                name="api_tool_discount_between_0_and_100",
            ),
        ),
    ]
