# Generated by Django 5.2.17 on 2026-08-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_sitesettings_api_tool_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_gateway',
            field=models.CharField(choices=[('cpay', 'CPay'), ('cryptapi', 'CryptAPI')], default='cpay', help_text='Provider that creates and confirms new USDT BEP20 deposits', max_length=16),
        ),
    ]
