# Generated by Django 5.2.17 on 2026-08-31 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_remove_sitesettings_payment_gateway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsageEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=120)),
                ('method', models.CharField(max_length=8)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('external_user_id', models.CharField(blank=True, default='', max_length=255)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='api.apikey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_usage_user_created_idx'), models.Index(fields=['api_key', '-created_at'], name='api_usage_key_created_idx'), models.Index(fields=['status_code', '-created_at'], name='api_usage_status_created_idx')],
            },
        ),
    ]
