# Generated by Django 5.2.3 on 2026-02-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='S9K3-41TV', max_length=20),
        ),
    ]
