# Generated by Django 5.2.17 on 2026-08-15 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTwoFactorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_secret', models.TextField()),
                ('recovery_code_hashes', models.JSONField(blank=True, default=list)),
                ('confirmed_at', models.DateTimeField()),
                ('last_used_counter', models.BigIntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_two_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin two-factor profile',
                'verbose_name_plural': 'admin two-factor profiles',
            },
        ),
    ]
