# Generated by Django 5.2.17 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_admintwofactorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintwofactorprofile',
            name='last_settings_counter',
            field=models.BigIntegerField(default=-1),
        ),
    ]
