"""
Django settings for serverConfig project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the .env file in the backend directory
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Environment configuration
ENV = os.getenv("ENV", "development")  # default to development

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+#ds1yk1fdrx$=3&yf+!q$r9sy!l$vjl8ea@_fhya_t3(okl!p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', ".vercel.app", ".now.sh", ".vercel.sh", "127.0.0.1", "9bad-102-89-68-147.ngrok-free.app", "api.sharptoolz.com", "38.242.198.49"]

# Application definition
INSTALLED_APPS = [ 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    "rest_framework",
    'rest_framework.authtoken',
    'dj_rest_auth',
    'corsheaders',
    
    'channels',
    
    #local apps
    "accounts",
    "api",
    "wallet",
    "analytics",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # GZip must be high in the stack for API responses
    'django.middleware.http.ConditionalGetMiddleware',  # Adds ETag support
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add custom middleware for media CORS in development
if ENV == "development":
    MIDDLEWARE.append('serverConfig.middleware.MediaCorsMiddleware')

ROOT_URLCONF = 'serverConfig.urls'


ASGI_APPLICATION = 'serverConfig.asgi.application'


if ENV == "production":
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.environ.get("REDIS_URL", "redis://localhost:6379")],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'serverConfig.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if ENV == "production" and os.getenv("DATABASE_URL"):
    DATABASES = {
        'default': {
            **dj_database_url.parse(os.getenv("DATABASE_URL")),
            'CONN_MAX_AGE': 600,  # Connection lifetime
            'ATOMIC_REQUESTS': False,  # Disable for better performance
            'AUTOCOMMIT': True,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploaded content)
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Add Cross-Origin-Resource-Policy header for development
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'

# Django 4.2+ Storages configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000

# Create temp uploads directory if it doesn't exist
if ENV == "production":
    # Use system temp directory in production
    import tempfile
    FILE_UPLOAD_TEMP_DIR = tempfile.gettempdir()
else:
    # Use local temp_uploads directory in development
    temp_uploads_dir = os.path.join(BASE_DIR, 'temp_uploads')
    if not os.path.exists(temp_uploads_dir):
        os.makedirs(temp_uploads_dir, exist_ok=True)
    FILE_UPLOAD_TEMP_DIR = temp_uploads_dir

# Additional upload settings for better performance
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
]

# Additional settings for large file uploads
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Increase request body size limit for large SVG files
REQUEST_BODY_SIZE_LIMIT = 100 * 1024 * 1024  # 100MB

# Cache Configuration for better performance
# Use Redis for caching in production, fallback to local memory cache in development
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/1")

if ENV == "production":
    try:
        import django_redis
        CACHES = {
            'default': {
                'BACKEND': 'django_redis.cache.RedisCache',
                'LOCATION': REDIS_URL,
                'OPTIONS': {
                    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                },
                'KEY_PREFIX': 'sharptoolz',
                'TIMEOUT': 300,  # Default timeout: 5 minutes
            }
        }
    except (ImportError, Exception) as e:
        print(f"Warning: Redis cache configured but not available. Error: {e}")
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'unique-snowflake',
            }
        }
else:
    # Use local memory cache for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# testing1


#  Custom Settings
AUTH_USER_MODEL = 'accounts.User'

REST_AUTH = {
    'LOGIN_SERIALIZER': 'accounts.serializers.LoginSerializer',
    "USER_DETAILS_SERIALIZER": "accounts.serializers.CustomUserDetailsSerializer",
}

REST_AUTH_SERIALIZERS = {
    "USER_DETAILS_SERIALIZER": "accounts.serializers.CustomUserDetailsSerializer",
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.JWTAuthenticationFromCookies',
    ),
}

# AUTHENTICATION_BACKENDS = [
#     'accounts.backends.EmailBackend',
#     'django.contrib.auth.backends.ModelBackend'
# ]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "https://docs-maker-demo.vercel.app",
    "http://localhost:3000",
    "https://order-tracker-demo.vercel.app",
    "https://sharptoolz.com",
    "https://parcelfinda.com",
    "http://38.242.198.49",
    "https://myflightlookup.com",
    "https://api.sharptoolz.com",
]

CORS_ORIGIN_WHITELIST = [
    "http://localhost:5173",
    "http://localhost:5174",
    "https://docs-maker-demo.vercel.app",
    "http://localhost:3000",
    "https://order-tracker-demo.vercel.app",
    "https://sharptoolz.com",
    "http://38.242.198.49",
    "https://parcelfinda.com",
    "https://myflightlookup.com",
    "https://api.sharptoolz.com",
]

# Additional CORS settings to fix image loading in development
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins in development
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']

# CSRF Trusted Origins - Required for CSRF validation
CSRF_TRUSTED_ORIGINS = [
    "https://api.sharptoolz.com",  # Add your API domain
    "https://myflightlookup.com",
    "https://sharptoolz.com",
    "https://parcelfinda.com",
    "https://myflightlookup.com",
]

JWT_COOKIE_SAMESITE = 'None'  # Allow cross-site cookies
JWT_COOKIE_SECURE = True      # Must be True if using HTTPS
JWT_COOKIE_HTTPONLY = True    # Prevent XSS
JWT_COOKIE_PATH = '/'         # Available site-wide

CSRF_COOKIE_SAMESITE = 'None'     # Allow cross-site cookies (for use with HTTPS)
CSRF_COOKIE_SECURE = True         # Cookie only sent over HTTPS
CSRF_COOKIE_HTTPONLY = False      # CSRF cookie must be accessible via JavaScript
CSRF_COOKIE_PATH = '/' 

SESSION_COOKIE_SAMESITE = 'None'     # Allow cross-site cookies (for use with HTTPS)
SESSION_COOKIE_SECURE = True         # Cookie only sent over HTTPS
SESSION_COOKIE_HTTPONLY = False      # CSRF cookie must be accessible via JavaScript
SESSION_COOKIE_PATH = '/' 

# # JWT / Auth cookies
# JWT_COOKIE_SAMESITE = 'Lax'
# JWT_COOKIE_SECURE = False
# JWT_COOKIE_HTTPONLY = True
# JWT_COOKIE_PATH = '/'

# # CSRF
# CSRF_COOKIE_SAMESITE = 'Lax'
# CSRF_COOKIE_SECURE = False
# CSRF_COOKIE_HTTPONLY = False
# CSRF_COOKIE_PATH = '/'

# # Session (if used)
# SESSION_COOKIE_SAMESITE = 'Lax'
# SESSION_COOKIE_SECURE = False
# SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_PATH = '/'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # 'ROTATE_REFRESH_TOKENS': False,
    # 'BLACKLIST_AFTER_ROTATION': False,
    'SIGNING_KEY': 'your-secret-key-here',  # use env var in prod
}

SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Set to 'mandatory' if needed

FRONTEND_URL = os.getenv("FRONTEND_URL")  # or your production frontend

# Remove.bg API configuration
REMOVEBG_API_KEY = os.getenv("REMOVEBG_API_KEY")

# And configure your email backend:
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER')

# Security Settings
SECURITY_CODE = os.getenv('SECURITY_CODE', '123456')