"""
Django settings for serverConfig project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import sys
from dotenv import load_dotenv
import dj_database_url
import sentry_sdk
from corsheaders.defaults import default_headers
from sentry_sdk.integrations.django import DjangoIntegration

# Initialize Sentry
sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN", "https://1295c1d6e0e0b4c1162044587fe2ecae@o4511259828158464.ingest.us.sentry.io/4511259830255616"),
    integrations=[DjangoIntegration()],
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    traces_sample_rate=1.0,
    # API keys, embed tokens, document values and customer cookies must never be
    # copied into an external error tracker.
    send_default_pii=False,
    max_request_body_size="never",
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the .env file in the backend directory
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Environment configuration
ENV = os.getenv("ENV", "development")  # default to development
IS_PRODUCTION = ENV == "production"

def env_int(name, default):
    try:
        return int(os.getenv(name, default))
    except (TypeError, ValueError):
        return default


def env_bool(name, default=False):
    return os.getenv(name, "True" if default else "False").strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default):
    """Comma-separated env override with a code default (same pattern as ALLOWED_HOSTS)."""
    raw = os.getenv(name)
    values = default if raw is None else raw.split(",")
    return [item.strip() for item in values if item and item.strip()]


# Senior Optimization: Lower CONN_MAX_AGE for small RAM servers
# 20-30 seconds is better than 60 if RAM is tight.
DB_CONN_MAX_AGE = env_int("DB_CONN_MAX_AGE", 20 if IS_PRODUCTION else 0)
DB_CONNECT_TIMEOUT = env_int("DB_CONNECT_TIMEOUT", 10)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-+#ds1yk1fdrx$=3&yf+!q$r9sy!l$vjl8ea@_fhya_t3(okl!p')
API_KEY_PEPPER = os.getenv("API_KEY_PEPPER", "" if IS_PRODUCTION else SECRET_KEY)
ADMIN_2FA_ENCRYPTION_KEY = os.getenv("ADMIN_2FA_ENCRYPTION_KEY", SECRET_KEY)
ADMIN_2FA_ISSUER = os.getenv("ADMIN_2FA_ISSUER", "SharpToolz")
ADMIN_2FA_CHALLENGE_SECONDS = env_int("ADMIN_2FA_CHALLENGE_SECONDS", 600)
ADMIN_2FA_MAX_ATTEMPTS = env_int("ADMIN_2FA_MAX_ATTEMPTS", 5)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True" if IS_PRODUCTION else True

# ALLOWED_HOSTS is driven from the env so prod can change hosts without a code
# deploy. Defaults cover local dev + tests; prod sets the real list via Dokploy.
ALLOWED_HOSTS = [h.strip() for h in os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,testserver"
).split(",") if h.strip()]

# Application definition
INSTALLED_APPS = [ 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    "rest_framework",
    "drf_spectacular",
    'rest_framework.authtoken',
    'dj_rest_auth',
    'corsheaders',
    
    'channels',
    'django_celery_beat',
    'axes',

    #local apps
    "accounts",
    "api",
    "wallet",
    "analytics",
]

MIDDLEWARE = [
    # Rewrite REMOTE_ADDR from X-Forwarded-For FIRST so every other middleware
    # (security, sessions, throttles, axes) sees the real client IP.
    'serverConfig.middleware.TrustedProxyMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'serverConfig.middleware.ApiRequestSizeMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # GZip must be high in the stack for API responses
    'django.middleware.http.ConditionalGetMiddleware',  # Adds ETag support
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'analytics.middleware.VisitorTrackingMiddleware',
    # axes must be the LAST middleware so it sees auth failures after auth
    'axes.middleware.AxesMiddleware',
]

if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')
    INSTALLED_APPS.append('django_extensions')
    # Should be after GZipMiddleware
    MIDDLEWARE.insert(MIDDLEWARE.index('django.middleware.gzip.GZipMiddleware') + 1, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = [
        "127.0.0.1",
    ]

# Add custom middleware for media CORS in development
if ENV == "development":
    MIDDLEWARE.append('serverConfig.middleware.MediaCorsMiddleware')

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Number of trusted proxies between the client and Django.
# 0 = no proxy (dev). 1 = single proxy hop (Cloudflare / one nginx).
# Set higher only if you have multiple proxies you control.
# Used by TrustedProxyMiddleware AND propagated to DRF throttles below.
TRUSTED_PROXY_HOPS = int(os.getenv('TRUSTED_PROXY_HOPS', '1' if IS_PRODUCTION else '0'))


ROOT_URLCONF = 'serverConfig.urls'


ASGI_APPLICATION = 'serverConfig.asgi.application'

API_RENDER_WATCH_TTL_SECONDS = env_int("API_RENDER_WATCH_TTL_SECONDS", 60)


if ENV == "production":
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.environ.get("REDIS_URL", "redis://localhost:6379")],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'serverConfig.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

if ENV == "production" and DATABASE_URL:
    database_config = dj_database_url.parse(DATABASE_URL)
    database_options = dict(database_config.get('OPTIONS', {}))
    database_options.setdefault('connect_timeout', DB_CONNECT_TIMEOUT)

    DATABASES = {
        'default': {
            **database_config,
            'CONN_MAX_AGE': DB_CONN_MAX_AGE,
            'CONN_HEALTH_CHECKS': True,
            'ATOMIC_REQUESTS': False,  # Disable for better performance
            'AUTOCOMMIT': True,
            'OPTIONS': database_options,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploaded content)
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cross-origin / referrer
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
SECURE_REFERRER_POLICY = 'same-origin' if IS_PRODUCTION else 'no-referrer-when-downgrade'

# Production-only hardening. The edge proxy must use Full (strict) TLS to the
# origin; Flexible TLS is not acceptable for authenticated or paid API traffic.
if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", True)
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    assert not DEBUG, "DEBUG must be False in production"

# Django 4.2+ Storages configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Optional shared private object storage. The web and Celery worker must see the
# same media backend for render outputs; without these variables, deployments
# must mount one shared /app/media volume into both services.
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
if AWS_STORAGE_BUCKET_NAME:
    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
    AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]
    AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
    AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN") or None
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = env_int("AWS_QUERYSTRING_EXPIRE", 300)
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    STORAGES["default"] = {"BACKEND": "api.storage_backends.MediaStorage"}

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000

# Create temp uploads directory if it doesn't exist
if ENV == "production":
    # Use system temp directory in production
    import tempfile
    FILE_UPLOAD_TEMP_DIR = tempfile.gettempdir()
else:
    # Use local temp_uploads directory in development
    temp_uploads_dir = os.path.join(BASE_DIR, 'temp_uploads')
    if not os.path.exists(temp_uploads_dir):
        os.makedirs(temp_uploads_dir, exist_ok=True)
    FILE_UPLOAD_TEMP_DIR = temp_uploads_dir

# Additional upload settings for better performance
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
]

# Additional settings for large file uploads
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Increase request body size limit for large SVG files
REQUEST_BODY_SIZE_LIMIT = 100 * 1024 * 1024  # 100MB
API_V1_MAX_REQUEST_BYTES = env_int("API_V1_MAX_REQUEST_BYTES", 25 * 1024 * 1024)
API_DASHBOARD_MAX_REQUEST_BYTES = env_int("API_DASHBOARD_MAX_REQUEST_BYTES", 256 * 1024)
API_RENDER_MAX_SVG_BYTES = env_int("API_RENDER_MAX_SVG_BYTES", 50 * 1024 * 1024)
API_RENDER_MAX_PIXELS = env_int("API_RENDER_MAX_PIXELS", 25_000_000)
API_RENDER_MAX_DIMENSION = env_int("API_RENDER_MAX_DIMENSION", 8_192)
API_RENDER_MAX_OUTPUT_BYTES = env_int("API_RENDER_MAX_OUTPUT_BYTES", 50 * 1024 * 1024)
API_RENDER_RETENTION_HOURS = env_int("API_RENDER_RETENTION_HOURS", 24)
API_RENDER_MAX_ACTIVE_PER_KEY = env_int("API_RENDER_MAX_ACTIVE_PER_KEY", 10)
API_RENDER_MAX_ACTIVE_PER_USER = env_int("API_RENDER_MAX_ACTIVE_PER_USER", 20)
API_RENDER_STORAGE_BYTES_PER_USER = env_int("API_RENDER_STORAGE_BYTES_PER_USER", 1024 ** 3)
API_EMBED_MAX_PENDING_PER_KEY = env_int("API_EMBED_MAX_PENDING_PER_KEY", 500)

# Cache Configuration for better performance
# Use Redis for caching in production, fallback to local memory cache in development
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/1")

if ENV == "production":
    try:
        import django_redis
        CACHES = {
            'default': {
                'BACKEND': 'django_redis.cache.RedisCache',
                'LOCATION': REDIS_URL,
                'OPTIONS': {
                    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                },
                'KEY_PREFIX': 'sharptoolz',
                'TIMEOUT': 300,  # Default timeout: 5 minutes
            }
        }
    except (ImportError, Exception) as e:
        print(f"Warning: Redis cache configured but not available. Error: {e}")
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'unique-snowflake',
            }
        }
else:
    # Use local memory cache for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# testing1


#  Custom Settings
AUTH_USER_MODEL = 'accounts.User'

REST_AUTH = {
    'LOGIN_SERIALIZER': 'accounts.serializers.LoginSerializer',
    "USER_DETAILS_SERIALIZER": "accounts.serializers.CustomUserDetailsSerializer",
}

REST_AUTH_SERIALIZERS = {
    "USER_DETAILS_SERIALIZER": "accounts.serializers.CustomUserDetailsSerializer",
}

REST_FRAMEWORK = {
    'NUM_PROXIES': TRUSTED_PROXY_HOPS,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.JWTAuthenticationFromCookies',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        # Baseline limits — tune in env if needed
        'anon': os.getenv('THROTTLE_ANON', '120/min' if IS_PRODUCTION else '1000/min'),
        'user': os.getenv('THROTTLE_USER', '300/min' if IS_PRODUCTION else '1000/min'),
        # Scoped throttles (per-view) — keep tight on sensitive endpoints in production
        'auth_login':    os.getenv('THROTTLE_AUTH_LOGIN',    '5/min' if IS_PRODUCTION else '120/min'),
        'auth_register': os.getenv('THROTTLE_AUTH_REGISTER', '5/min' if IS_PRODUCTION else '120/min'),
        'auth_password': os.getenv('THROTTLE_AUTH_PASSWORD', '5/min' if IS_PRODUCTION else '120/min'),
        'wallet_write':  os.getenv('THROTTLE_WALLET_WRITE',  '20/min' if IS_PRODUCTION else '120/min'),
        'analytics_ingest': os.getenv('THROTTLE_ANALYTICS_INGEST', '120/min' if IS_PRODUCTION else '1000/min'),
        'admin_read':    os.getenv('THROTTLE_ADMIN_READ',    '600/min' if IS_PRODUCTION else '2000/min'),
        'admin_2fa':     os.getenv('THROTTLE_ADMIN_2FA',     '10/min' if IS_PRODUCTION else '120/min'),
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'SharpToolz API',
    'DESCRIPTION': 'Multi-tenant document API and hosted-form sessions.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/api/v1',
    'SCHEMA_PATH_PREFIX_TRIM': True,
    'COMPONENT_SPLIT_REQUEST': True,
    'PREPROCESSING_HOOKS': ['api.schema.filter_public_v1_endpoints'],
    'SERVERS': [{'url': '/api/v1', 'description': 'SharpToolz API v1'}],
}

# -----------------------------------------------------------------------------
# Celery — broker + result backend on Redis.
# Worker concurrency caps DB connections; size it to match Postgres budget.
# -----------------------------------------------------------------------------
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_TIME_LIMIT = 60
CELERY_TASK_SOFT_TIME_LIMIT = 45
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Run tasks inline under the test runner so the suite never needs a live broker.
TESTING = "test" in sys.argv
if TESTING:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = False

# Rate-limit cache (django-ratelimit reads from default cache)
RATELIMIT_USE_CACHE = "default"
RATELIMIT_ENABLE = os.getenv("RATELIMIT_ENABLE", "True") == "True"

# django-axes MUST sit at the top of AUTHENTICATION_BACKENDS so it can
# intercept failed logins before any other backend authenticates.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ---------------------------------------------------------------------------
# django-axes — brute-force protection
# Configured VPN-safe: lockouts apply to the USERNAME only, never the IP.
# That way users sharing a VPN exit IP can't lock each other out.
# ---------------------------------------------------------------------------
AXES_ENABLED = os.getenv('AXES_ENABLED', 'True' if IS_PRODUCTION else 'False') == 'True'
AXES_FAILURE_LIMIT = int(os.getenv('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = timedelta(minutes=int(os.getenv('AXES_COOLOFF_MIN', '30')))
AXES_LOCK_OUT_AT_FAILURE = True
AXES_RESET_ON_SUCCESS = True
# v6 unified config: lock by username only — VPN-safe.
AXES_LOCKOUT_PARAMETERS = ['username']
AXES_IPWARE_PROXY_COUNT = TRUSTED_PROXY_HOPS
AXES_IPWARE_META_PRECEDENCE_ORDER = ('HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR')
AXES_DISABLE_ACCESS_LOG = False
AXES_VERBOSE = not IS_PRODUCTION
AXES_CACHE = 'default'

# ---------------------------------------------------------------------------
# CORS / CSRF
#
# The dashboard is a separate origin from the API, and the browser sends the
# JWT as a cookie, so EVERY browser origin needs two grants:
#   1. CORS_ALLOWED_ORIGINS   -> the browser is allowed to read the response
#   2. CSRF_TRUSTED_ORIGINS   -> Django accepts its POST/PUT/PATCH/DELETE
# Granting only the first produces a 403 "Origin checking failed" on write,
# which reads like a CORS bug but is not one. Keep the two lists in step.
#
# Customer embeds do NOT belong here: the hosted form runs in an iframe served
# from FRONTEND_URL, so its requests carry the sharptoolz.com origin and the
# customer's own domain arrives in the X-Embed-Origin header instead.
#
# Both lists are env-driven so a new domain ships without a code deploy.
# ---------------------------------------------------------------------------
CORS_ALLOW_CREDENTIALS = True

# Local dev servers. Non-production only — never grant these in production, or
# any page on a developer's machine can drive the live API with real cookies.
LOCAL_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Browser origins that call the API.
DEFAULT_CORS_ORIGINS = [
    "https://sharptoolz.com",
    "https://api.sharptoolz.com",
    "https://cdn.sharptoolz.com",
    "https://dev.sharptoolz.com",
    "https://devapi.sharptoolz.com",
    "https://parcelfinda.com",
    "https://myflightlookup.com",
    "https://docs-maker-demo.vercel.app",
    "https://order-tracker-demo.vercel.app",
    "http://38.242.198.49",
]

# Origins trusted to send unsafe methods. Narrower than the CORS list: the
# demo deployments may read, but they may not write with a user's cookies.
DEFAULT_CSRF_ORIGINS = [
    "https://sharptoolz.com",
    "https://api.sharptoolz.com",
    "https://cdn.sharptoolz.com",
    "https://dev.sharptoolz.com",
    "https://devapi.sharptoolz.com",
    "https://parcelfinda.com",
    "https://myflightlookup.com",
]

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    DEFAULT_CORS_ORIGINS if IS_PRODUCTION else DEFAULT_CORS_ORIGINS + LOCAL_ORIGINS,
)

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    DEFAULT_CSRF_ORIGINS if IS_PRODUCTION else DEFAULT_CSRF_ORIGINS + LOCAL_ORIGINS,
)

# Echoing back any origin while allowing credentials means any website can read
# authenticated responses, so it is limited to local development. Staging and
# every other deployed env authenticate real users and must use the list above.
CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", ENV == "development")

CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
CORS_ALLOW_HEADERS = (*default_headers, 'x-embed-origin', 'idempotency-key')

# Dashboard and API subdomains are same-site, so cross-site cookies are not
# required. Hosted customer embeds authenticate with a scoped bearer session.
COOKIE_SAMESITE = os.getenv('COOKIE_SAMESITE', 'Lax')

# Secure cookies are mandatory in production. Local dev runs on plain http, and
# Safari drops Secure cookies there even on localhost, so default it off when
# not in production rather than relying on a browser special case.
COOKIE_SECURE = env_bool("COOKIE_SECURE", IS_PRODUCTION)

JWT_COOKIE_SAMESITE = COOKIE_SAMESITE
JWT_COOKIE_SECURE = COOKIE_SECURE
JWT_COOKIE_HTTPONLY = True
JWT_COOKIE_PATH = '/'

CSRF_COOKIE_SAMESITE = COOKIE_SAMESITE
CSRF_COOKIE_SECURE = COOKIE_SECURE
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_PATH = '/'

SESSION_COOKIE_SAMESITE = COOKIE_SAMESITE
SESSION_COOKIE_SECURE = COOKIE_SECURE
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_PATH = '/'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MIN', '30'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'SIGNING_KEY': os.getenv('JWT_SIGNING_KEY', SECRET_KEY),
}
if IS_PRODUCTION:
    signing_key = SIMPLE_JWT["SIGNING_KEY"] or ""
    weak_secret = (
        len(SECRET_KEY) < 50
        or len(set(SECRET_KEY)) < 8
        or SECRET_KEY.startswith("django-insecure-")
    )
    weak_signing_key = (
        len(signing_key) < 50
        or len(set(signing_key)) < 8
        or signing_key == "your-secret-key-here"
    )
    weak_api_pepper = len(API_KEY_PEPPER) < 50 or len(set(API_KEY_PEPPER)) < 8
    weak_admin_2fa_key = len(ADMIN_2FA_ENCRYPTION_KEY) < 50 or len(set(ADMIN_2FA_ENCRYPTION_KEY)) < 8
    if weak_secret or weak_signing_key or weak_api_pepper or weak_admin_2fa_key:
        raise RuntimeError("SECRET_KEY, JWT_SIGNING_KEY, API_KEY_PEPPER, and ADMIN_2FA_ENCRYPTION_KEY must be strong production secrets")

SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Set to 'mandatory' if needed

FRONTEND_URL = os.getenv("FRONTEND_URL")  # or your production frontend

# Remove.bg API configuration
REMOVEBG_API_KEY = os.getenv("REMOVEBG_API_KEY")

# And configure your email backend:
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
# Django defaults to no timeout, which lets a wedged mail server hold a worker
# open indefinitely. Bound every SMTP conversation instead.
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', 10))

# Defined after the block above so it wins over the SMTP backend.
if TESTING:
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"

# Security Settings
SECURITY_CODE = os.getenv('SECURITY_CODE', '123456')

# Google OAuth
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')

# AI Chat
AI_API_KEY = os.getenv("AI_API_KEY")
AI_BASE_URL = os.getenv("AI_BASE_URL", "https://openrouter.ai/api/v1")
AI_MODEL = os.getenv("AI_MODEL", "openai/gpt-4o")
