# Generated by Django 5.2.3 on 2026-07-04 00:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_referral_balance_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='DepositBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_granted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('spent', 'Spent'), ('expired', 'Expired')], default='active', max_length=10)),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_bonuses', to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='wallet.wallet')),
            ],
            options={
                'ordering': ['expires_at', 'granted_at'],
                'indexes': [models.Index(fields=['wallet', 'status'], name='wallet_depo_wallet__e3ef29_idx'), models.Index(fields=['expires_at'], name='wallet_depo_expires_6da8bc_idx')],
            },
        ),
    ]
