# Generated by Django 5.2.17 on 2026-08-29 18:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallet_bonus_balance_depositbonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPayDepositRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpay_client_id', models.CharField(max_length=64, unique=True)),
                ('cpay_wallet_id', models.CharField(max_length=128, unique=True)),
                ('cpay_address', models.CharField(max_length=128, unique=True)),
                ('encrypted_passphrase', models.TextField()),
                ('encrypted_callback_nonce', models.TextField()),
                ('cryptapi_callback_url', models.TextField()),
                ('cryptapi_address_in', models.CharField(blank=True, max_length=128)),
                ('cryptapi_callback_id', models.CharField(blank=True, max_length=128)),
                ('cryptapi_txid_in', models.CharField(blank=True, max_length=255)),
                ('cryptapi_txid_out', models.CharField(blank=True, max_length=255)),
                ('forwarded_amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('created', 'Created'), ('forwarded', 'Forwarded'), ('failed', 'Failed')], default='created', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpay_route', to='wallet.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptAPIWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callback_id', models.CharField(max_length=128, unique=True)),
                ('txid_in', models.CharField(max_length=255, unique=True)),
                ('txid_out', models.CharField(blank=True, max_length=255)),
                ('amount_forwarded', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credited_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cryptapi_event', to='wallet.transaction')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='wallet.cpaydepositroute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueDistributionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('threshold_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=6, max_digits=18)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('sending', 'Sending'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('failed', 'Failed')], default='preparing', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='wallet_reve_status_73f3ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevenueDistributionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('last_available_balance', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('last_balance_checked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('threshold_amount__gt', 0)), name='revenue_distribution_threshold_positive')],
            },
        ),
        migrations.CreateModel(
            name='RevenueShareRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('bep20_address', models.CharField(max_length=42)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('percentage__gt', 0), ('percentage__lte', 100)), name='revenue_recipient_percentage_valid'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email',), name='unique_active_revenue_recipient_email'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('bep20_address',), name='unique_active_revenue_recipient_address')],
            },
        ),
        migrations.CreateModel(
            name='RevenueDistributionPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=120)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('bep20_address', models.CharField(max_length=42)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=128)),
                ('transaction_hash', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='wallet.revenuedistributionbatch')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='wallet.revenuesharerecipient')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cpaydepositroute',
            constraint=models.UniqueConstraint(condition=models.Q(('cryptapi_callback_id', ''), _negated=True), fields=('cryptapi_callback_id',), name='unique_nonempty_cryptapi_callback_id'),
        ),
        migrations.AddConstraint(
            model_name='cpaydepositroute',
            constraint=models.UniqueConstraint(condition=models.Q(('cryptapi_txid_in', ''), _negated=True), fields=('cryptapi_txid_in',), name='unique_nonempty_cryptapi_txid_in'),
        ),
        migrations.AddIndex(
            model_name='revenuedistributionpayout',
            index=models.Index(fields=['status', '-created_at'], name='wallet_reve_status_f3b338_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenuedistributionpayout',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), fields=('provider_transaction_id',), name='unique_nonempty_cpay_payout_transaction'),
        ),
    ]
