# Generated by Django 5.2.17 on 2026-08-29 22:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_rename_cpay_client_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpaydepositroute',
            name='cpay_transaction_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='cpaydepositroute',
            name='cpay_tx_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cpaydepositroute',
            name='route_type',
            field=models.CharField(choices=[('cpay', 'Legacy CPay direct'), ('cryptapi_cpay', 'CryptAPI to CPay bridge')], default='cryptapi_cpay', max_length=24),
        ),
        migrations.AlterField(
            model_name='cpaydepositroute',
            name='cryptapi_callback_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cpaydepositroute',
            name='encrypted_callback_nonce',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CPayWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_transaction_id', models.CharField(max_length=128, unique=True)),
                ('tx_hash', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credited_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cpay_event', to='wallet.transaction')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpay_webhook_events', to='wallet.cpaydepositroute')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tx_hash', ''), _negated=True), fields=('tx_hash',), name='unique_nonempty_cpay_tx_hash')],
            },
        ),
    ]
