# Generated by Django 5.2.17 on 2026-09-08 06:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_cryptapiwebhookevent_deposit_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='revenuedistributionpayout',
            name='signed_transaction',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='OnChainDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('chain_id', models.PositiveBigIntegerField(default=56)),
                ('token_contract', models.CharField(max_length=42)),
                ('sender_address', models.CharField(max_length=42)),
                ('recipient_address', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('credited_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('block_number', models.PositiveBigIntegerField()),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmations'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onchain_deposit', to='wallet.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='wallet_onch_status_d2e073_idx')],
            },
        ),
    ]
